# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd90f4b32f8b14988bf8cda156f58023d046bbc77c6af76e2b5b72fa9107f0e87beb07bf470060e9e4aad8bd9de2efdd1f2c281a57410eab26849e2d2fcd8de7

test:
  secret_key_base: 00378412a8d90519f0a757f99cf152298af587403676d897ba837c58bf994674418872cd2e2b45d93d928cbaf9194f02bfddae42e7e48dca79e85d574fb0f1d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
